package com.gighub.common.api;

/**
 * 보호 명세에서 외부 공개를 승인한 공통 오류 코드입니다.
 *
 * <p>도메인별 세부 오류 카탈로그가 확정되기 전에는 이 목록 안에서만 응답 코드를 선택합니다.</p>
 */
public enum ApiErrorCode {
    VALIDATION_ERROR,
    AUTH_REQUIRED,
    FORBIDDEN,
    ROLE_MISMATCH,
    RESOURCE_NOT_FOUND,
    CONFLICT,
    IDEMPOTENCY_KEY_REUSED,
    WORK_CASE_LOCKED,
    INVITATION_EXPIRED,
    INVITATION_REVOKED,
    INVITATION_ALREADY_ACCEPTED,
    INVITATION_TERMS_CHANGED,
    CONTRACT_RETENTION_REQUIRED,
    QR_INVALID,
    QR_REVOKED,
    WORKPLACE_LOCATION_REQUIRED,
    WORKPLACE_ADDRESS_NOT_RESOLVABLE,
    WORKPLACE_GEOCODING_TEMPORARILY_UNAVAILABLE,
    LOCATION_INVALID,
    OUTSIDE_WORKPLACE_RADIUS,
    ATTENDANCE_WORK_CASE_NOT_FOUND,
    ATTENDANCE_WORK_CASE_AMBIGUOUS,
    ATTENDANCE_ALREADY_COMPLETED,
    ATTENDANCE_STATE_CONFLICT,
    ATTENDANCE_TEMPORARILY_UNAVAILABLE,
    SETTLEMENT_ON_HOLD,
    SETTLEMENT_NOT_READY,
    SETTLEMENT_ALREADY_PROCESSED,
    SETTLEMENT_TEMPORARILY_UNAVAILABLE,
    INTERNAL_ERROR
}
