-- GigHub 참고용 최종 스키마 스냅샷
-- NOT A FLYWAY MIGRATION
-- 기준: MySQL 8.4.10 / Flyway head 202608121403 / Migration 19개 / 도메인 테이블 24개 (2026-08-12 확인)
-- 단일 원본: backend/src/main/resources/db/migration/V*.sql
-- 대상: 빈 데이터베이스. 기존 DB 업그레이드에는 사용하지 않는다.
-- 제외: 데이터, flyway_schema_history, DROP 문, 실행 환경의 AUTO_INCREMENT 현재값

SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
SET @GIGHUB_OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @GIGHUB_OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `attendance_records` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `work_case_id` bigint unsigned NOT NULL,
  `worker_id` bigint unsigned NOT NULL,
  `qr_token_id` bigint unsigned DEFAULT NULL,
  `attendance_type` varchar(20) NOT NULL,
  `captured_at` datetime(6) NOT NULL,
  `attempted_at` datetime(6) NOT NULL,
  `distance_meters` decimal(10,2) DEFAULT NULL,
  `accuracy_meters` decimal(10,2) DEFAULT NULL,
  `result` varchar(20) NOT NULL,
  `failure_reason` varchar(100) DEFAULT NULL,
  `early_checkout_confirmed_at` datetime(6) DEFAULT NULL,
  `success_slot` tinyint GENERATED ALWAYS AS ((case when (`result` = _utf8mb4'SUCCESS') then 1 else NULL end)) STORED,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_attendance_records_success` (`work_case_id`,`attendance_type`,`success_slot`),
  KEY `idx_attendance_records_case_type_created` (`work_case_id`,`attendance_type`,`created_at`),
  KEY `idx_attendance_records_worker_created` (`worker_id`,`created_at`),
  KEY `fk_attendance_records_qr_token` (`qr_token_id`),
  CONSTRAINT `fk_attendance_records_qr_token` FOREIGN KEY (`qr_token_id`) REFERENCES `qr_tokens` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_attendance_records_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_attendance_records_worker` FOREIGN KEY (`worker_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_attendance_records_accuracy` CHECK (((`accuracy_meters` is null) or (`accuracy_meters` >= 0))),
  CONSTRAINT `ck_attendance_records_distance` CHECK (((`distance_meters` is null) or (`distance_meters` >= 0))),
  CONSTRAINT `ck_attendance_records_early_checkout_confirmation` CHECK (((`early_checkout_confirmed_at` is null) or ((`attendance_type` = _utf8mb4'CHECK_OUT') and (`result` = _utf8mb4'SUCCESS')))),
  CONSTRAINT `ck_attendance_records_result` CHECK ((`result` in (_utf8mb4'SUCCESS',_utf8mb4'REJECTED'))),
  CONSTRAINT `ck_attendance_records_type` CHECK ((`attendance_type` in (_utf8mb4'CHECK_IN',_utf8mb4'CHECK_OUT')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `disputes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `work_case_id` bigint unsigned NOT NULL,
  `requester_id` bigint unsigned NOT NULL,
  `dispute_type` varchar(30) NOT NULL,
  `title` varchar(100) NOT NULL,
  `content` text NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'OPEN',
  `resolution` text,
  `resolved_by_user_id` bigint unsigned DEFAULT NULL,
  `resolved_at` datetime(6) DEFAULT NULL,
  `open_slot` tinyint GENERATED ALWAYS AS ((case when (`status` in (_utf8mb4'OPEN',_utf8mb4'UNDER_REVIEW')) then 1 else NULL end)) STORED,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_disputes_open` (`work_case_id`,`open_slot`),
  KEY `idx_disputes_status_created` (`status`,`created_at`),
  KEY `fk_disputes_requester` (`requester_id`),
  KEY `fk_disputes_resolver` (`resolved_by_user_id`),
  CONSTRAINT `fk_disputes_requester` FOREIGN KEY (`requester_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_disputes_resolver` FOREIGN KEY (`resolved_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_disputes_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_disputes_status` CHECK ((`status` in (_utf8mb4'OPEN',_utf8mb4'UNDER_REVIEW',_utf8mb4'RESOLVED',_utf8mb4'REJECTED',_utf8mb4'CANCELED'))),
  CONSTRAINT `ck_disputes_title` CHECK (((`title` = trim(`title`)) and (char_length(`title`) between 1 and 100)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `document_access_logs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `document_id` bigint unsigned NOT NULL,
  `document_version_id` bigint unsigned DEFAULT NULL COMMENT '접근 대상으로 확정된 문서 Version; 기존 행 또는 Version 확정 전 거부는 NULL',
  `actor_user_id` bigint unsigned DEFAULT NULL,
  `action` varchar(30) NOT NULL,
  `result` varchar(20) NOT NULL,
  `denial_reason` varchar(50) CHARACTER SET ascii COLLATE ascii_bin DEFAULT NULL COMMENT 'DENIED 결과의 구조화된 내부 사유 Code; 기존 행은 NULL',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  KEY `idx_document_access_logs_document_created` (`document_id`,`created_at`),
  KEY `idx_document_access_logs_actor_created` (`actor_user_id`,`created_at`),
  KEY `idx_document_access_logs_document_version_created` (`document_id`,`document_version_id`,`created_at`),
  CONSTRAINT `fk_document_access_logs_actor` FOREIGN KEY (`actor_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_document_access_logs_document` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_document_access_logs_document_version` FOREIGN KEY (`document_id`, `document_version_id`) REFERENCES `document_versions` (`document_id`, `id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_document_access_logs_action` CHECK ((`action` in (_utf8mb4'HEALTH_CERT_FILE_VIEW',_utf8mb4'HEALTH_CERT_FILE_DOWNLOAD',_utf8mb4'CONTRACT_FILE_VIEW',_utf8mb4'CONTRACT_FILE_DOWNLOAD',_utf8mb4'DOCUMENT_DETAIL_VIEW'))),
  CONSTRAINT `ck_document_access_logs_denial_reason` CHECK (((`denial_reason` is null) or ((`result` = _utf8mb4'DENIED') and (`denial_reason` in (_utf8mb4'PARTY_ACCESS_DENIED',_utf8mb4'DOCUMENT_UNAVAILABLE',_utf8mb4'FILE_UNAVAILABLE',_utf8mb4'CHECKSUM_MISMATCH',_utf8mb4'SIGNED_VERSION_UNAVAILABLE'))))),
  CONSTRAINT `ck_document_access_logs_result` CHECK ((`result` in (_utf8mb4'ALLOWED',_utf8mb4'DENIED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `document_shares` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `document_id` bigint unsigned NOT NULL,
  `work_case_id` bigint unsigned NOT NULL,
  `shared_with_user_id` bigint unsigned NOT NULL,
  `purpose` varchar(30) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `expires_at` datetime(6) DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `active_slot` tinyint GENERATED ALWAYS AS ((case when (`status` = _utf8mb4'ACTIVE') then 1 else NULL end)) STORED,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_document_shares_active` (`document_id`,`work_case_id`,`shared_with_user_id`,`purpose`,`active_slot`),
  KEY `idx_document_shares_recipient_status_expiry` (`shared_with_user_id`,`status`,`expires_at`),
  KEY `fk_document_shares_work_case` (`work_case_id`),
  CONSTRAINT `fk_document_shares_document` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_document_shares_recipient` FOREIGN KEY (`shared_with_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_document_shares_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_document_shares_purpose` CHECK ((`purpose` in (_utf8mb4'CONTRACT_PARTY',_utf8mb4'HEALTH_CERTIFICATE'))),
  CONSTRAINT `ck_document_shares_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'EXPIRED',_utf8mb4'REVOKED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `document_signatures` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `document_id` bigint unsigned NOT NULL,
  `source_version_id` bigint unsigned NOT NULL,
  `signed_version_id` bigint unsigned NOT NULL,
  `signer_user_id` bigint unsigned NOT NULL,
  `source_checksum` binary(32) NOT NULL,
  `signed_checksum` binary(32) NOT NULL,
  `typed_name` varchar(100) NOT NULL,
  `signature_method` varchar(20) NOT NULL,
  `consented_at` datetime(6) NOT NULL,
  `signed_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_document_signatures_signed_version` (`signed_version_id`),
  UNIQUE KEY `uk_document_signatures_once` (`document_id`,`source_version_id`,`signer_user_id`),
  KEY `fk_document_signatures_signed_version` (`document_id`,`signed_version_id`),
  KEY `fk_document_signatures_signer` (`signer_user_id`),
  CONSTRAINT `fk_document_signatures_signed_version` FOREIGN KEY (`document_id`, `signed_version_id`) REFERENCES `document_versions` (`document_id`, `id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_document_signatures_signer` FOREIGN KEY (`signer_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_document_signatures_source_version` FOREIGN KEY (`document_id`, `source_version_id`) REFERENCES `document_versions` (`document_id`, `id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_document_signatures_method` CHECK ((`signature_method` in (_utf8mb4'TYPED_NAME',_utf8mb4'DRAWN'))),
  CONSTRAINT `ck_document_signatures_time` CHECK ((`signed_at` >= `consented_at`)),
  CONSTRAINT `ck_document_signatures_versions` CHECK ((`source_version_id` <> `signed_version_id`))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `document_versions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `document_id` bigint unsigned NOT NULL,
  `version_no` int unsigned NOT NULL,
  `version_type` varchar(20) NOT NULL,
  `storage_key` varchar(255) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `mime_type` varchar(100) NOT NULL,
  `size_bytes` bigint unsigned NOT NULL,
  `checksum` binary(32) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_document_versions_storage_key` (`storage_key`),
  UNIQUE KEY `uk_document_versions_document_version` (`document_id`,`version_no`),
  UNIQUE KEY `uk_document_versions_document_id_id` (`document_id`,`id`),
  KEY `idx_document_versions_type_created` (`document_id`,`version_type`,`created_at`),
  CONSTRAINT `fk_document_versions_document` FOREIGN KEY (`document_id`) REFERENCES `documents` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_document_versions_number` CHECK ((`version_no` >= 1)),
  CONSTRAINT `ck_document_versions_size` CHECK ((`size_bytes` > 0)),
  CONSTRAINT `ck_document_versions_type` CHECK ((`version_type` in (_utf8mb4'ORIGINAL',_utf8mb4'SIGNED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `documents` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_by_user_id` bigint unsigned NOT NULL,
  `owner_user_id` bigint unsigned NOT NULL,
  `work_case_id` bigint unsigned DEFAULT NULL,
  `document_type` varchar(30) NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'DRAFT',
  `issued_on` date DEFAULT NULL,
  `expires_on` date DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_documents_work_case_type` (`work_case_id`,`document_type`),
  KEY `idx_documents_owner_status_created` (`owner_user_id`,`status`,`created_at`),
  KEY `fk_documents_creator` (`created_by_user_id`),
  CONSTRAINT `fk_documents_creator` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_documents_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_documents_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_documents_expiry` CHECK (((`expires_on` is null) or (`issued_on` is null) or (`expires_on` >= `issued_on`))),
  CONSTRAINT `ck_documents_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'AWAITING_SIGNATURE',_utf8mb4'SIGNED',_utf8mb4'ACTIVE',_utf8mb4'CANCELED',_utf8mb4'DELETED'))),
  CONSTRAINT `ck_documents_type` CHECK ((`document_type` in (_utf8mb4'EMPLOYMENT_CONTRACT',_utf8mb4'HEALTH_CERTIFICATE')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `escrows` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `work_case_id` bigint unsigned NOT NULL,
  `amount` bigint unsigned NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'UNFUNDED',
  `held_at` datetime(6) DEFAULT NULL,
  `released_at` datetime(6) DEFAULT NULL,
  `refunded_at` datetime(6) DEFAULT NULL,
  `on_hold_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_escrows_work_case_id` (`work_case_id`),
  KEY `fk_escrows_case_wage` (`work_case_id`,`amount`),
  CONSTRAINT `fk_escrows_case_wage` FOREIGN KEY (`work_case_id`, `amount`) REFERENCES `work_cases` (`id`, `agreed_wage`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_escrows_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_escrows_amount` CHECK ((`amount` > 0)),
  CONSTRAINT `ck_escrows_lifecycle` CHECK ((((`status` = _utf8mb4'UNFUNDED') and (`held_at` is null) and (`released_at` is null) and (`refunded_at` is null) and (`on_hold_at` is null)) or ((`status` = _utf8mb4'HELD') and (`held_at` is not null) and (`released_at` is null) and (`refunded_at` is null) and (`on_hold_at` is null)) or ((`status` = _utf8mb4'RELEASED') and (`held_at` is not null) and (`released_at` is not null) and (`released_at` >= `held_at`) and (`refunded_at` is null) and (`on_hold_at` is null)) or ((`status` = _utf8mb4'REFUNDED') and (`held_at` is not null) and (`refunded_at` is not null) and (`refunded_at` >= `held_at`) and (`released_at` is null) and (`on_hold_at` is null)) or (`status` = _utf8mb4'ON_HOLD'))),
  CONSTRAINT `ck_escrows_status` CHECK ((`status` in (_utf8mb4'UNFUNDED',_utf8mb4'HELD',_utf8mb4'RELEASED',_utf8mb4'REFUNDED',_utf8mb4'ON_HOLD')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `funding_orders` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `employer_id` bigint unsigned NOT NULL,
  `linked_account_id` bigint unsigned NOT NULL,
  `expected_amount` bigint unsigned NOT NULL,
  `transferred_amount` bigint unsigned DEFAULT NULL,
  `mock_bank_transaction_id` bigint unsigned DEFAULT NULL,
  `idempotency_key` varchar(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'READY',
  `failure_code` varchar(50) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_funding_orders_idempotency_key` (`idempotency_key`),
  UNIQUE KEY `uk_funding_orders_bank_transaction` (`mock_bank_transaction_id`),
  KEY `idx_funding_orders_employer_status_created` (`employer_id`,`status`,`created_at`),
  KEY `fk_funding_orders_linked_account` (`linked_account_id`),
  CONSTRAINT `fk_funding_orders_bank_transaction` FOREIGN KEY (`mock_bank_transaction_id`) REFERENCES `mock_bank_transactions` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_funding_orders_employer` FOREIGN KEY (`employer_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_funding_orders_linked_account` FOREIGN KEY (`linked_account_id`) REFERENCES `mock_bank_accounts` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_funding_orders_expected_amount` CHECK ((`expected_amount` > 0)),
  CONSTRAINT `ck_funding_orders_lifecycle` CHECK ((((`status` = _utf8mb4'READY') and (`transferred_amount` is null) and (`mock_bank_transaction_id` is null) and (`failure_code` is null) and (`completed_at` is null)) or ((`status` = _utf8mb4'COMPLETED') and (`transferred_amount` is not null) and (`transferred_amount` = `expected_amount`) and (`mock_bank_transaction_id` is not null) and (`failure_code` is null) and (`completed_at` is not null)) or (`status` in (_utf8mb4'FAILED',_utf8mb4'RECONCILIATION_REQUIRED')))),
  CONSTRAINT `ck_funding_orders_status` CHECK ((`status` in (_utf8mb4'READY',_utf8mb4'COMPLETED',_utf8mb4'FAILED',_utf8mb4'RECONCILIATION_REQUIRED'))),
  CONSTRAINT `ck_funding_orders_transferred_amount` CHECK (((`transferred_amount` is null) or (`transferred_amount` > 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `idempotency_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL COMMENT '요청 인증 사용자',
  `operation_code` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '멱등성 적용 Operation',
  `idempotency_key` varchar(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '클라이언트 원본 Key',
  `request_fingerprint` binary(32) NOT NULL COMMENT '정규화 요청의 32바이트 Fingerprint',
  `status` varchar(20) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT 'PROCESSING' COMMENT 'PROCESSING 또는 COMPLETED',
  `response_http_status` smallint unsigned DEFAULT NULL COMMENT '최초 성공 응답 HTTP 상태',
  `response_body` json DEFAULT NULL COMMENT '최초 성공 응답 JSON Snapshot',
  `completed_at` datetime(6) DEFAULT NULL COMMENT '성공 처리 완료 시각',
  `expires_at` datetime(6) NOT NULL COMMENT 'Claim 보존 만료 시각',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_idempotency_requests_scope` (`user_id`,`operation_code`,`idempotency_key`),
  CONSTRAINT `fk_idempotency_requests_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_idempotency_requests_expiry` CHECK (((`expires_at` > `created_at`) and ((`completed_at` is null) or ((`completed_at` >= `created_at`) and (`completed_at` <= `expires_at`))))),
  CONSTRAINT `ck_idempotency_requests_http_status` CHECK (((`response_http_status` is null) or (`response_http_status` between 200 and 299))),
  CONSTRAINT `ck_idempotency_requests_key` CHECK ((char_length(`idempotency_key`) > 0)),
  CONSTRAINT `ck_idempotency_requests_lifecycle` CHECK ((((`status` = _utf8mb4'PROCESSING') and (`response_http_status` is null) and (`response_body` is null) and (`completed_at` is null)) or ((`status` = _utf8mb4'COMPLETED') and (`response_http_status` is not null) and (`response_body` is not null) and (`completed_at` is not null)))),
  CONSTRAINT `ck_idempotency_requests_operation` CHECK ((char_length(`operation_code`) > 0)),
  CONSTRAINT `ck_idempotency_requests_status` CHECK ((`status` in (_utf8mb4'PROCESSING',_utf8mb4'COMPLETED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='멱등 요청 Claim과 성공 응답 저장';

CREATE TABLE `mock_bank_accounts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `bank_code` char(3) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `mock_account_number` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `pin` char(4) CHARACTER SET ascii COLLATE ascii_bin NOT NULL DEFAULT '0000',
  `mock_fintech_use_num` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'KRW',
  `balance` bigint unsigned NOT NULL DEFAULT '0',
  `available_amount` bigint unsigned NOT NULL DEFAULT '0',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mock_bank_accounts_fintech_use_num` (`mock_fintech_use_num`),
  UNIQUE KEY `uk_mock_bank_accounts_bank_account` (`bank_code`,`mock_account_number`),
  CONSTRAINT `ck_mock_bank_accounts_account_number` CHECK ((char_length(trim(`mock_account_number`)) > 0)),
  CONSTRAINT `ck_mock_bank_accounts_amounts` CHECK ((`available_amount` <= `balance`)),
  CONSTRAINT `ck_mock_bank_accounts_bank_code` CHECK (regexp_like(`bank_code`,_ascii'^[0-9]{3}$')),
  CONSTRAINT `ck_mock_bank_accounts_currency` CHECK ((`currency` = _utf8mb4'KRW')),
  CONSTRAINT `ck_mock_bank_accounts_pin` CHECK (regexp_like(`pin`,_utf8mb4'^[0-9]{4}$')),
  CONSTRAINT `ck_mock_bank_accounts_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'BLOCKED',_utf8mb4'CLOSED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `mock_bank_transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `account_id` bigint unsigned NOT NULL,
  `bank_tran_id` varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `transfer_type` varchar(20) NOT NULL,
  `amount` bigint unsigned NOT NULL,
  `balance_before` bigint unsigned NOT NULL,
  `balance_after` bigint unsigned NOT NULL,
  `reference_type` varchar(30) NOT NULL,
  `reference_id` bigint unsigned NOT NULL,
  `status` varchar(20) NOT NULL,
  `failure_code` varchar(50) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_mock_bank_transactions_bank_tran_id` (`bank_tran_id`),
  UNIQUE KEY `uk_mock_bank_transactions_reference` (`reference_type`,`reference_id`,`transfer_type`),
  KEY `idx_mock_bank_transactions_account_created` (`account_id`,`created_at`),
  CONSTRAINT `fk_mock_bank_transactions_account` FOREIGN KEY (`account_id`) REFERENCES `mock_bank_accounts` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_mock_bank_transactions_amount` CHECK ((`amount` > 0)),
  CONSTRAINT `ck_mock_bank_transactions_status` CHECK ((`status` in (_utf8mb4'READY',_utf8mb4'PROCESSING',_utf8mb4'SUCCESS',_utf8mb4'FAILED'))),
  CONSTRAINT `ck_mock_bank_transactions_transfer_type` CHECK ((`transfer_type` in (_utf8mb4'WITHDRAW',_utf8mb4'DEPOSIT')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `password_reset_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `token_hash` binary(32) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `expires_at` datetime(6) NOT NULL,
  `used_at` datetime(6) DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `active_slot` tinyint GENERATED ALWAYS AS ((case when (`status` = _utf8mb4'ACTIVE') then 1 else NULL end)) STORED,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_password_reset_tokens_token_hash` (`token_hash`),
  UNIQUE KEY `uk_password_reset_tokens_user_active` (`user_id`,`active_slot`),
  KEY `idx_password_reset_tokens_status_expiry` (`status`,`expires_at`),
  CONSTRAINT `fk_password_reset_tokens_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_password_reset_tokens_lifecycle` CHECK ((((`status` = _utf8mb4'ACTIVE') and (`used_at` is null) and (`revoked_at` is null)) or ((`status` = _utf8mb4'USED') and (`used_at` is not null) and (`revoked_at` is null)) or ((`status` = _utf8mb4'EXPIRED') and (`used_at` is null) and (`revoked_at` is null)) or ((`status` = _utf8mb4'REVOKED') and (`used_at` is null) and (`revoked_at` is not null)))),
  CONSTRAINT `ck_password_reset_tokens_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'USED',_utf8mb4'EXPIRED',_utf8mb4'REVOKED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `qr_tokens` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `workplace_id` bigint unsigned NOT NULL,
  `legacy_work_case_id` bigint unsigned DEFAULT NULL,
  `issued_by_user_id` bigint unsigned NOT NULL,
  `legacy_token_hash` binary(32) DEFAULT NULL,
  `token_nonce` binary(16) DEFAULT NULL,
  `legacy_action` varchar(20) DEFAULT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `legacy_expires_at` datetime(6) DEFAULT NULL,
  `legacy_used_at` datetime(6) DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `active_slot` tinyint GENERATED ALWAYS AS ((case when ((`token_nonce` is not null) and (`status` = _utf8mb4'ACTIVE')) then 1 else NULL end)) STORED,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_qr_tokens_legacy_token_hash` (`legacy_token_hash`),
  UNIQUE KEY `uk_qr_tokens_token_nonce` (`token_nonce`),
  UNIQUE KEY `uk_qr_tokens_workplace_active` (`workplace_id`,`active_slot`),
  KEY `idx_qr_tokens_workplace_status_created` (`workplace_id`,`status`,`created_at`),
  KEY `idx_qr_tokens_legacy_case_action_created` (`legacy_work_case_id`,`legacy_action`,`created_at`),
  KEY `fk_qr_tokens_workplace_issuer` (`issued_by_user_id`,`workplace_id`),
  CONSTRAINT `fk_qr_tokens_legacy_work_case` FOREIGN KEY (`legacy_work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_qr_tokens_workplace_issuer` FOREIGN KEY (`issued_by_user_id`, `workplace_id`) REFERENCES `workplaces` (`owner_user_id`, `id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_qr_tokens_legacy_action` CHECK (((`legacy_action` is null) or (`legacy_action` in (_utf8mb4'CHECK_IN',_utf8mb4'CHECK_OUT')))),
  CONSTRAINT `ck_qr_tokens_revoked_at` CHECK ((((`status` = _utf8mb4'REVOKED') and (`revoked_at` is not null)) or ((`status` <> _utf8mb4'REVOKED') and (`revoked_at` is null)))),
  CONSTRAINT `ck_qr_tokens_shape` CHECK ((((`token_nonce` is not null) and (`legacy_token_hash` is null) and (`legacy_work_case_id` is null) and (`legacy_action` is null) and (`legacy_expires_at` is null) and (`legacy_used_at` is null) and (`status` in (_utf8mb4'ACTIVE',_utf8mb4'REVOKED'))) or ((`token_nonce` is null) and (`legacy_token_hash` is not null) and (`legacy_work_case_id` is not null) and (`legacy_action` is not null) and (`legacy_expires_at` is not null) and (`status` in (_utf8mb4'USED',_utf8mb4'EXPIRED',_utf8mb4'REVOKED'))))),
  CONSTRAINT `ck_qr_tokens_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'USED',_utf8mb4'EXPIRED',_utf8mb4'REVOKED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `settlements` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `work_case_id` bigint unsigned NOT NULL,
  `amount` bigint unsigned NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'WAITING',
  `approved_by_user_id` bigint unsigned DEFAULT NULL,
  `due_at` datetime(6) DEFAULT NULL,
  `processing_at` datetime(6) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `failure_code` varchar(50) DEFAULT NULL,
  `retry_count` tinyint unsigned NOT NULL DEFAULT '0',
  `last_failure_at` datetime(6) DEFAULT NULL,
  `next_retry_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_settlements_work_case_id` (`work_case_id`),
  KEY `idx_settlements_status_due_at` (`status`,`due_at`),
  KEY `fk_settlements_approver` (`approved_by_user_id`),
  KEY `fk_settlements_case_wage` (`work_case_id`,`amount`),
  CONSTRAINT `fk_settlements_approver` FOREIGN KEY (`approved_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_settlements_case_wage` FOREIGN KEY (`work_case_id`, `amount`) REFERENCES `work_cases` (`id`, `agreed_wage`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_settlements_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_settlements_amount` CHECK ((`amount` > 0)),
  CONSTRAINT `ck_settlements_lifecycle` CHECK ((((`status` = _utf8mb4'WAITING') and (`approved_by_user_id` is null) and (`due_at` is null) and (`processing_at` is null) and (`completed_at` is null) and (`failure_code` is null) and (`retry_count` = 0) and (`last_failure_at` is null) and (`next_retry_at` is null)) or ((`status` in (_utf8mb4'SCHEDULED',_utf8mb4'ON_HOLD')) and (`approved_by_user_id` is null) and (`due_at` is not null) and (`processing_at` is null) and (`completed_at` is null) and (((`retry_count` = 0) and (`failure_code` is null) and (`last_failure_at` is null) and (`next_retry_at` is null)) or ((`retry_count` between 1 and 4) and (`failure_code` is not null) and (`last_failure_at` is not null) and (`next_retry_at` is not null)))) or ((`status` = _utf8mb4'PROCESSING') and (`processing_at` is not null) and (`completed_at` is null) and (`failure_code` is null) and (`next_retry_at` is null) and ((`due_at` is not null) or (`approved_by_user_id` is not null)) and (((`retry_count` = 0) and (`last_failure_at` is null)) or ((`retry_count` between 1 and 4) and (`last_failure_at` is not null)))) or ((`status` = _utf8mb4'COMPLETED') and (`due_at` is not null) and (`processing_at` is not null) and (`completed_at` is not null) and (`failure_code` is null) and (`next_retry_at` is null) and (((`retry_count` = 0) and (`last_failure_at` is null)) or ((`retry_count` between 1 and 4) and (`last_failure_at` is not null)))) or ((`status` = _utf8mb4'REFUNDED') and (`approved_by_user_id` is not null) and (`due_at` is null) and (`processing_at` is not null) and (`completed_at` is not null) and (`failure_code` is null) and (`retry_count` = 0) and (`last_failure_at` is null) and (`next_retry_at` is null)) or ((`status` = _utf8mb4'FAILED') and (`approved_by_user_id` is null) and (`due_at` is not null) and (`processing_at` is null) and (`completed_at` is null) and (`failure_code` is not null) and (`retry_count` between 1 and 5) and (`last_failure_at` is not null) and (`next_retry_at` is null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_badges` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `badge_type` varchar(40) NOT NULL,
  `evidence` json NOT NULL,
  `awarded_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_badges_user_type` (`user_id`,`badge_type`),
  CONSTRAINT `fk_user_badges_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_user_badges_type` CHECK ((`badge_type` in (_utf8mb4'TRUST_OWNER',_utf8mb4'TRUST_WORKER')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `users` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `login_id` varchar(50) NOT NULL,
  `email` varchar(255) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `name` varchar(100) NOT NULL,
  `phone` varchar(30) DEFAULT NULL,
  `role` varchar(20) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `deleted_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_users_email` (`email`),
  UNIQUE KEY `uk_users_login_id` (`login_id`),
  CONSTRAINT `ck_users_role` CHECK ((`role` in (_utf8mb4'OWNER',_utf8mb4'WORKER',_utf8mb4'ADMIN'))),
  CONSTRAINT `ck_users_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'INACTIVE',_utf8mb4'LOCKED',_utf8mb4'WITHDRAWN'))),
  CONSTRAINT `ck_users_withdrawn_at` CHECK ((((`status` = _utf8mb4'WITHDRAWN') and (`deleted_at` is not null)) or ((`status` <> _utf8mb4'WITHDRAWN') and (`deleted_at` is null))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wallet_transactions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `wallet_id` bigint unsigned NOT NULL,
  `work_case_id` bigint unsigned DEFAULT NULL,
  `transaction_type` varchar(30) NOT NULL,
  `amount` bigint unsigned NOT NULL,
  `available_before` bigint unsigned NOT NULL,
  `available_after` bigint unsigned NOT NULL,
  `locked_before` bigint unsigned NOT NULL,
  `locked_after` bigint unsigned NOT NULL,
  `reference_type` varchar(30) NOT NULL,
  `reference_id` bigint unsigned NOT NULL,
  `idempotency_key` varchar(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wallet_transactions_idempotency_key` (`idempotency_key`),
  KEY `idx_wallet_transactions_wallet_created` (`wallet_id`,`created_at`),
  KEY `idx_wallet_transactions_work_case_created` (`work_case_id`,`created_at`),
  CONSTRAINT `fk_wallet_transactions_wallet` FOREIGN KEY (`wallet_id`) REFERENCES `wallets` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_wallet_transactions_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_wallet_transactions_amount` CHECK ((`amount` > 0)),
  CONSTRAINT `ck_wallet_transactions_type` CHECK ((`transaction_type` in (_utf8mb4'FUNDING',_utf8mb4'ESCROW_HOLD',_utf8mb4'ESCROW_RELEASE',_utf8mb4'ESCROW_REFUND',_utf8mb4'WITHDRAWAL',_utf8mb4'WITHDRAWAL_REFUND',_utf8mb4'ADJUSTMENT')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wallets` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `currency` char(3) NOT NULL DEFAULT 'KRW',
  `available_balance` bigint unsigned NOT NULL DEFAULT '0',
  `locked_balance` bigint unsigned NOT NULL DEFAULT '0',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_wallets_user_currency` (`user_id`,`currency`),
  CONSTRAINT `fk_wallets_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_wallets_currency` CHECK ((`currency` = _utf8mb4'KRW'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `withdrawal_requests` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint unsigned NOT NULL,
  `wallet_id` bigint unsigned NOT NULL,
  `linked_account_id` bigint unsigned NOT NULL,
  `amount` bigint unsigned NOT NULL,
  `mock_bank_transaction_id` bigint unsigned DEFAULT NULL,
  `idempotency_key` varchar(100) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `status` varchar(30) NOT NULL DEFAULT 'READY',
  `failure_code` varchar(50) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_withdrawal_requests_idempotency_key` (`idempotency_key`),
  UNIQUE KEY `uk_withdrawal_requests_bank_transaction` (`mock_bank_transaction_id`),
  KEY `fk_withdrawal_requests_wallet` (`wallet_id`),
  KEY `fk_withdrawal_requests_linked_account` (`linked_account_id`),
  KEY `idx_withdrawal_requests_user_status_created` (`user_id`,`status`,`created_at`),
  CONSTRAINT `fk_withdrawal_requests_bank_transaction` FOREIGN KEY (`mock_bank_transaction_id`) REFERENCES `mock_bank_transactions` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_withdrawal_requests_linked_account` FOREIGN KEY (`linked_account_id`) REFERENCES `mock_bank_accounts` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_withdrawal_requests_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_withdrawal_requests_wallet` FOREIGN KEY (`wallet_id`) REFERENCES `wallets` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_withdrawal_requests_amount` CHECK ((`amount` > 0)),
  CONSTRAINT `ck_withdrawal_requests_lifecycle` CHECK ((((`status` = _utf8mb4'READY') and (`mock_bank_transaction_id` is null) and (`failure_code` is null) and (`completed_at` is null)) or ((`status` = _utf8mb4'COMPLETED') and (`mock_bank_transaction_id` is not null) and (`failure_code` is null) and (`completed_at` is not null)) or (`status` in (_utf8mb4'PROCESSING',_utf8mb4'FAILED',_utf8mb4'RECONCILIATION_REQUIRED')))),
  CONSTRAINT `ck_withdrawal_requests_status` CHECK ((`status` in (_utf8mb4'READY',_utf8mb4'PROCESSING',_utf8mb4'COMPLETED',_utf8mb4'FAILED',_utf8mb4'RECONCILIATION_REQUIRED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `work_cases` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `employer_id` bigint unsigned NOT NULL,
  `worker_id` bigint unsigned DEFAULT NULL,
  `workplace_id` bigint unsigned NOT NULL,
  `title` varchar(150) NOT NULL,
  `starts_at` datetime(6) NOT NULL,
  `ends_at` datetime(6) NOT NULL,
  `break_minutes` smallint unsigned NOT NULL DEFAULT '0',
  `break_paid` tinyint unsigned NOT NULL DEFAULT '0',
  `workplace_name` varchar(150) NOT NULL,
  `workplace_address` varchar(255) NOT NULL,
  `workplace_latitude` decimal(10,7) DEFAULT NULL,
  `workplace_longitude` decimal(10,7) DEFAULT NULL,
  `allowed_radius_meters` decimal(8,2) NOT NULL DEFAULT '100.00',
  `agreed_wage` bigint unsigned NOT NULL,
  `terms_version` int unsigned NOT NULL DEFAULT '1',
  `status` varchar(20) NOT NULL DEFAULT 'DRAFT',
  `canceled_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_work_cases_id_wage` (`id`,`agreed_wage`),
  UNIQUE KEY `uk_work_cases_id_parties_wage` (`id`,`employer_id`,`worker_id`,`agreed_wage`),
  KEY `idx_work_cases_employer_status_start` (`employer_id`,`status`,`starts_at`),
  KEY `idx_work_cases_worker_status_start` (`worker_id`,`status`,`starts_at`),
  KEY `idx_work_cases_status_start` (`status`,`starts_at`),
  KEY `idx_work_cases_workplace_status_start` (`workplace_id`,`status`,`starts_at`),
  KEY `idx_work_cases_employer_workplace` (`employer_id`,`workplace_id`),
  KEY `idx_work_cases_worker_workplace_status_start_end` (`worker_id`,`workplace_id`,`status`,`starts_at`,`ends_at`),
  CONSTRAINT `fk_work_cases_employer` FOREIGN KEY (`employer_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_work_cases_employer_workplace` FOREIGN KEY (`employer_id`, `workplace_id`) REFERENCES `workplaces` (`owner_user_id`, `id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_work_cases_worker` FOREIGN KEY (`worker_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_work_cases_break_paid` CHECK ((`break_paid` in (0,1))),
  CONSTRAINT `ck_work_cases_cancellation_lifecycle` CHECK ((((`status` = _utf8mb4'CANCELED') and (`canceled_at` is not null)) or ((`status` <> _utf8mb4'CANCELED') and (`canceled_at` is null)))),
  CONSTRAINT `ck_work_cases_coordinates` CHECK ((((`workplace_latitude` is null) and (`workplace_longitude` is null)) or ((`workplace_latitude` between -(90) and 90) and (`workplace_longitude` between -(180) and 180)))),
  CONSTRAINT `ck_work_cases_matched_worker` CHECK (((`status` not in (_utf8mb4'ACCEPTED',_utf8mb4'READY',_utf8mb4'IN_PROGRESS',_utf8mb4'CHECK_OUT_MISSING',_utf8mb4'COMPLETED',_utf8mb4'NO_SHOW')) or (`worker_id` is not null))),
  CONSTRAINT `ck_work_cases_radius` CHECK ((`allowed_radius_meters` > 0)),
  CONSTRAINT `ck_work_cases_status` CHECK ((`status` in (_utf8mb4'DRAFT',_utf8mb4'ACCEPTED',_utf8mb4'READY',_utf8mb4'IN_PROGRESS',_utf8mb4'CHECK_OUT_MISSING',_utf8mb4'COMPLETED',_utf8mb4'NO_SHOW',_utf8mb4'CANCELED'))),
  CONSTRAINT `ck_work_cases_terms_version` CHECK ((`terms_version` >= 1)),
  CONSTRAINT `ck_work_cases_time` CHECK ((`ends_at` > `starts_at`)),
  CONSTRAINT `ck_work_cases_wage` CHECK ((`agreed_wage` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `work_contracts` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `work_case_id` bigint unsigned NOT NULL,
  `employer_id` bigint unsigned NOT NULL,
  `worker_id` bigint unsigned NOT NULL,
  `title` varchar(150) NOT NULL,
  `starts_at` datetime(6) NOT NULL,
  `ends_at` datetime(6) NOT NULL,
  `break_minutes` smallint unsigned NOT NULL,
  `break_paid` tinyint unsigned NOT NULL DEFAULT '0',
  `workplace_name` varchar(150) NOT NULL,
  `workplace_address` varchar(255) NOT NULL,
  `workplace_latitude` decimal(10,7) DEFAULT NULL,
  `workplace_longitude` decimal(10,7) DEFAULT NULL,
  `allowed_radius_meters` decimal(8,2) NOT NULL,
  `agreed_wage` bigint unsigned NOT NULL,
  `source_terms_version` int unsigned NOT NULL,
  `terms_snapshot` json NOT NULL,
  `accepted_at` datetime(6) NOT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_work_contracts_work_case_id` (`work_case_id`),
  KEY `fk_work_contracts_employer` (`employer_id`),
  KEY `fk_work_contracts_worker` (`worker_id`),
  KEY `fk_work_contracts_case_parties_wage` (`work_case_id`,`employer_id`,`worker_id`,`agreed_wage`),
  CONSTRAINT `fk_work_contracts_case_parties_wage` FOREIGN KEY (`work_case_id`, `employer_id`, `worker_id`, `agreed_wage`) REFERENCES `work_cases` (`id`, `employer_id`, `worker_id`, `agreed_wage`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_work_contracts_employer` FOREIGN KEY (`employer_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_work_contracts_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_work_contracts_worker` FOREIGN KEY (`worker_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_work_contracts_break_paid` CHECK ((`break_paid` in (0,1))),
  CONSTRAINT `ck_work_contracts_terms_version` CHECK ((`source_terms_version` >= 1)),
  CONSTRAINT `ck_work_contracts_time` CHECK ((`ends_at` > `starts_at`)),
  CONSTRAINT `ck_work_contracts_wage` CHECK ((`agreed_wage` > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `work_invitations` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `work_case_id` bigint unsigned NOT NULL,
  `token_hash` binary(32) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'PENDING',
  `expected_terms_version` int unsigned NOT NULL,
  `expires_at` datetime(6) NOT NULL,
  `accepted_by_user_id` bigint unsigned DEFAULT NULL,
  `accepted_terms_version` int unsigned DEFAULT NULL,
  `accepted_at` datetime(6) DEFAULT NULL,
  `rejected_at` datetime(6) DEFAULT NULL,
  `revoked_at` datetime(6) DEFAULT NULL,
  `active_slot` tinyint GENERATED ALWAYS AS ((case when (`status` = _utf8mb4'PENDING') then 1 else NULL end)) STORED,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_work_invitations_token_hash` (`token_hash`),
  UNIQUE KEY `uk_work_invitations_active` (`work_case_id`,`active_slot`),
  KEY `idx_work_invitations_case_status_expiry` (`work_case_id`,`status`,`expires_at`),
  KEY `fk_work_invitations_accepted_user` (`accepted_by_user_id`),
  CONSTRAINT `fk_work_invitations_accepted_user` FOREIGN KEY (`accepted_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_work_invitations_work_case` FOREIGN KEY (`work_case_id`) REFERENCES `work_cases` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_work_invitations_status` CHECK ((`status` in (_utf8mb4'PENDING',_utf8mb4'ACCEPTED',_utf8mb4'REJECTED',_utf8mb4'REVOKED',_utf8mb4'EXPIRED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `workplaces` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `owner_user_id` bigint unsigned NOT NULL,
  `business_registration_number` char(10) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `name` varchar(120) NOT NULL,
  `representative_name` varchar(100) NOT NULL,
  `road_address` varchar(255) NOT NULL,
  `detail_address` varchar(100) DEFAULT NULL,
  `phone` varchar(30) NOT NULL,
  `latitude` decimal(10,7) DEFAULT NULL,
  `longitude` decimal(10,7) DEFAULT NULL,
  `radius_meters` decimal(8,2) NOT NULL DEFAULT '100.00',
  `status` varchar(20) NOT NULL DEFAULT 'ACTIVE',
  `deleted_at` datetime(6) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_workplaces_business_registration_number` (`business_registration_number`),
  UNIQUE KEY `uk_workplaces_owner_id` (`owner_user_id`,`id`),
  KEY `idx_workplaces_owner_status` (`owner_user_id`,`status`),
  CONSTRAINT `fk_workplaces_owner` FOREIGN KEY (`owner_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `ck_workplaces_business_registration_number` CHECK (regexp_like(`business_registration_number`,_ascii'^[0-9]{10}$')),
  CONSTRAINT `ck_workplaces_coordinates` CHECK ((((`latitude` is null) and (`longitude` is null)) or ((`latitude` is not null) and (`longitude` is not null) and (`latitude` between -(90) and 90) and (`longitude` between -(180) and 180)))),
  CONSTRAINT `ck_workplaces_deleted_at` CHECK ((((`status` = _utf8mb4'DELETED') and (`deleted_at` is not null)) or ((`status` <> _utf8mb4'DELETED') and (`deleted_at` is null)))),
  CONSTRAINT `ck_workplaces_detail_address` CHECK (((`detail_address` is null) or (char_length(trim(`detail_address`)) > 0))),
  CONSTRAINT `ck_workplaces_radius` CHECK ((`radius_meters` > 0)),
  CONSTRAINT `ck_workplaces_required_text` CHECK (((char_length(trim(`name`)) > 0) and (char_length(trim(`representative_name`)) > 0) and (char_length(trim(`road_address`)) > 0) and (char_length(trim(`phone`)) > 0))),
  CONSTRAINT `ck_workplaces_status` CHECK ((`status` in (_utf8mb4'ACTIVE',_utf8mb4'INACTIVE',_utf8mb4'DELETED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

SET FOREIGN_KEY_CHECKS = @GIGHUB_OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @GIGHUB_OLD_UNIQUE_CHECKS;
